### ISSUE TITLE
JRELoadError on macOS

### ISSUE THREAD

**Issue by SwiftWinds** [airsquared/blobsaver#17]
Whenever I try to start the Blobsaver app, it throws a JRELoadError. I am running the latest 11.0.1 JDK/JRE with the latest macOS 10.14.1. Also, the .jar file works just fine.

**Comment by airsquared** [comment]
Thanks for the bug report, I'll have this fixed in the next version. My application probably only works on Java 8. So you don't have to worry about it, I'm thinking of bundling the JRE with my application, but it would add ~100 MB in size. I could also request the user install 2 JRE's, but I'm not sure that would be as convenient.

**Comment by airsquared** [comment]
I will close this issue so progress can be tracked on issue #27.
