### ISSUE TITLE
Allow re-ordering of presets and allow more than 10 presets

### ISSUE THREAD

**Issue by bs286692** [airsquared/blobsaver#226]
**Describe the what you'd like**
Allow re-ordering of presets and allow more than 10 presets.

**Comment by PencilNotPen** [comment]
I'd also love to have more than 10 presets if possible, perhaps the right sidebar could just scroll up and down as more presets are added, to keep the program window size the same. Thanks!

**Comment by airsquared** [comment]
Please try the beta in #242, this adds support for unlimited saved devices.

**Comment by PencilNotPen** [comment]
Thanks! I’ll try it now. May I ask a couple questions? They’re unrelated but brief

1) is Blobsaver working to save 14.4.1 blobs? I know SHSH . Host briefly wasn’t working with 14.4.1 and required a quick fix to work

2) does blobsaver work when setting a generator with unc0ver v6.x, and does it still correctly read the matching Apnonce when generator is set with unc0ver v6.x? It uses a custom method of setting a generator I think, and some other tools like SHSH . Host do not currently respect it properly.

Thanks for your good work!

**Comment by airsquared** [comment]
1. I'm not aware of any issues with saving 14.4.1 blobs using blobsaver
2. Regardless of how you set the generator, blobsaver should be able to read it correctly because it uses a similar method to futurerestore (both actually use the libraries libimobiledevice/libirecovery)

If you have any more questions, feel free to open a [discussion](https://github.com/airsquared/blobsaver/discussions)

**Comment by airsquared** [comment]
Added in v3.0.
