### ISSUE TITLE
Wrong Update Version shown in Popup

### ISSUE THREAD

**Issue by SnowLeoo** [airsquared/blobsaver#275]
**Describe the bug**
If you installed the 2.6 Version of blobserver it will show you an message that there is an update available for 2.5.5 which doesn't make sense.

**Screenshots**
![053CaepvKb](https://user-images.githubusercontent.com/49914615/119389720-49a78e00-bccc-11eb-9c26-0ded69cdef68.png)

**Desktop:**
 - OS Version: Windows 10
 - iOS Device: (if applicable)
 - Blobsaver Beta 2.6 (3.0)

**Checklist (place an x between the brackets to mark as completed):**
 - [x] I have made sure I am on the latest version of blobsaver
 - [x] I have checked the blobsaver wiki to see if there is already a solution to my problem
 - [x] I have tried common troubleshooting tactics such as restarting my computer and reinstalling blobsaver

**Log(s)**
None

**Comment by theIuser** [comment]
as stated in the announcement of  the beta: #242 

The version number says v2.6, but it's actually a 3.0 beta. This is to differentiate from when the full version is released.
Because it's a beta, it will prompt you that a new update (v2.5.5) is available, even though that's an older version. To avoid the prompt, you can just click "ignore this version" the next time you see it.

so the dev is totally aware of this behavior.

**Comment by SnowLeoo** [comment]
oh okay thanks. i overread it
