### ISSUE TITLE
ARM support for linux

### ISSUE THREAD

**Issue by Ryan222222** [airsquared/blobsaver#281]
#242 only has a AMD64 deb, can you add arm64 support so I can run v3.0 on my raspberry pi

**Comment by airsquared** [comment]
Since GitHub Actions doesn't provide ARM runners, I can't compile it myself for ARM but it should be simple enough to compile blobsaver yourself:

1. Clone this repository
2. Compile [this](https://github.com/DanTheMann15/tsschecker) fork of tsschecker on your device and replace the file in `dist/linux/tsschecker` with your tsschecker compiled for ARM.
3. Install JDK 16 and run `./gradlew build` in the root of the repository and you should have the the files in the directory `build/distributions`
4. Optionally, for reading from connected devices, install `libimobiledevice` and `libirecovery`.
